on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: macos-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo $SIGNING_KEY | base64 -d > src/android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run: flutter pub get
        working-directory: src
      # run static analys code
      - run: flutter analyze
        working-directory: src
      # run  flutter widgets tests  and unit tests
      #- run: flutter test --coverage
      #  working-directory: src
      - run: flutter build apk --split-per-abi
        working-directory: src
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - uses: actions/upload-artifact@v1
        with:
          name: app-armeabi-v7a-release.apk
          path: src/build/app/outputs/apk/release/app-armeabi-v7a-release.apk

      - uses: actions/upload-artifact@v1
        with:
          name: app-arm64-v8a-release.apk
          path: src/build/app/outputs/apk/release/app-arm64-v8a-release.apk

      - uses: actions/upload-artifact@v1
        with:
          name: app-x86_64-release.apk
          path: src/build/app/outputs/apk/release/app-x86_64-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset 1
        id: upload-release-asset-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: src/build/app/outputs/apk/release/app-armeabi-v7a-release.apk
          asset_name: dog-scanner-${{steps.tag.outputs.tag}}-armeabi-v7a-release.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Upload Release Asset 2
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: src/build/app/outputs/apk/release/app-arm64-v8a-release.apk
          asset_name: dog-scanner-${{steps.tag.outputs.tag}}-arm64-v8a-release.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Upload Release Asset 3
        id: upload-release-asset-3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: src/build/app/outputs/apk/release/app-x86_64-release.apk
          asset_name: dog-scanner-${{steps.tag.outputs.tag}}-x86_64-release.apk
          asset_content_type: application/vnd.android.package-archive
